Repository Electron-Cash/Electron-Cash, pull requests merged in 2019-11, with the labels that each got.

#1664 Add BlockExplorer.one explorer
  lib/web.py
Labels: UX and usability

#1666 transaction.py: allow caching hashPrevouts, hashSequence, hashOutputs
  lib/transaction.py
Labels: performance / optimization

#1668 Satochip Plugin Support
  contrib/build-linux/appimage/Dockerfile_ub1604
  contrib/build-linux/appimage/_build.sh
  contrib/build-wine/_build.sh
  contrib/build-wine/deterministic.spec
  contrib/deterministic-build/requirements-satochip.txt
  contrib/osx/make_osx
  contrib/osx/osx.spec
  gui/qt/icons.py
  icons.qrc
  icons/satochip.png
  icons/satochip_unpaired.png
  lib/plugins.py
  plugins/satochip/CardConnector.py
  plugins/satochip/CardDataParser.py
  plugins/satochip/JCconstants.py
  plugins/satochip/README.rst
  plugins/satochip/TxParser.py
  plugins/satochip/__init__.py
  plugins/satochip/ecc.py
  plugins/satochip/qt.py
  plugins/satochip/satochip.py
  plugins/satochip/zzbroken_test_CardConnector.py
  plugins/satochip_2FA/__init__.py
  plugins/satochip_2FA/qt.py
  setup.py
Labels: enhancement, hardware wallets

#1669 Plugins: Fix to @hook / @run_hook mechanism
  lib/plugins.py
Labels: Nits / Refactoring

#1673 Add crash reporter to prefs, Crash reporter layout fixes, & Prefs Layout fixes
  gui/qt/exception_window.py
  gui/qt/main_window.py
Labels: Qt, UX and usability

#1670 allow plugins to register daemon commands using decorator
  electron-cash
  lib/commands.py
  lib/daemon.py
  lib/plugins.py
Labels: Command Line, enhancement

#1678 tweak daemon command collisions in BasePlugin
  lib/plugins.py
Labels: Command Line, Nits / Refactoring

#1690 Android (phase 4): Add ability to delete closed wallets
  android/app/src/main/java/org/electroncash/electroncash3/Main.kt
Labels: UX and usability, android

#1695 softer shutdown on Ctrl-C / SIGINT
  gui/qt/__init__.py
Labels: Qt, enhancement

#1693 Misc mainline changes from fusion
  gui/qt/address_list.py
  lib/schnorr.py
  lib/tests/test_schnorr.py
  tox.ini
Labels: Cash Fusion, enhancement

#1696 README - add instructions for pyenv
  README.rst
Labels: Documentation
