Repository Electron-Cash/Electron-Cash, pull requests merged in 2019-08, with the labels that each got.

#1558 TxDialog: Improve in/outputs text-selection behaviour
  gui/qt/transaction_dialog.py
  gui/qt/util.py
Labels: Qt, UX and usability

#1561 Windows: Add manifest and upgrade PyInstaller to 3.5
  contrib/base.sh
  contrib/build-wine/_build.sh
  contrib/build-wine/deterministic.spec
  contrib/build-wine/manifest.xml
Labels: Windows, enhancement, packaging

#1567 Remove pip from requirements files
  contrib/deterministic-build/requirements-binaries-osx.txt
  contrib/deterministic-build/requirements-binaries.txt
  contrib/deterministic-build/requirements-hw.txt
  contrib/deterministic-build/requirements.txt
  contrib/freeze_packages.sh
Labels: packaging, performance / optimization

#1568 Add secp256k1 for Android
  contrib/deterministic-build/requirements-android.txt
  lib/secp256k1.py
Labels: android, performance / optimization

#1569 Payment Requests: Added BitPay 2.0 JSON API
  gui/qt/main_window.py
  lib/paymentrequest.py
  lib/web.py
Labels: enhancement

#1571 clean up ngettext().format()
  gui/qt/transaction_dialog.py
  lib/wallet.py
Labels: bug, i18n & Translation

#1577 Localization: Make age and time_difference function translatable
  lib/util.py
Labels: Nits / Refactoring, i18n & Translation

#1580 OSX: Fixups for Mojave visual & font glitches
  contrib/deterministic-build/requirements-binaries-elcapitan.txt
  contrib/osx/make_osx
  contrib/requirements/requirements-binaries-elcapitan.txt
  gui/qt/__init__.py
Labels: Qt, macOS, packaging, workarounds

#1582 add blind signature mechanism to schnorr.py
  lib/schnorr.py
  lib/secp256k1.py
  lib/tests/test_schnorr.py
Labels: Cash Fusion, enhancement

#1584 Console: Make warning fit in default window size
  gui/qt/console.py
Labels: Qt, UX and usability

#1589 Add a ruby script to update the Xcode project to avoid requiring manu…
  ios/make_ios_project.sh
  ios/update_project.rb
Labels: ios, packaging

#1593 Add Bip38 encryption capability to the class bitcoin.Bip38Key
  lib/bitcoin.py
  lib/tests/test_bitcoin.py
  tox.ini
Labels: enhancement

#1594 Add BIP38 Encryption to the GUI
  gui/qt/main_window.py
  gui/qt/password_dialog.py
Labels: Qt, enhancement
