Repository Electron-Cash/Electron-Cash, pull requests merged in 2019-01, with the labels that each got.

#1097 [Qt] Rename icons_rc.py -> icons.py, add icons.py to repository
  .gitignore
  README.rst
  contrib/build-wine/build-electrum-git.sh
  contrib/osx/make_osx
  electron-env
  gui/qt/__init__.py
  gui/qt/icons.py
  snap/snapcraft.yaml
Labels: packaging

#1098 [Qt] Anti-Phishing: Network Dialog Whitelist and Blacklist (user editable)
  gui/qt/network_dialog.py
  lib/network.py
  lib/networks.py
Labels: Security & Privacy, UX and usability, enhancement

#1114 [Qt] [Cosigner Pool] Fixed a bunch of bugs and refactored code
  gui/qt/transaction_dialog.py
  gui/qt/util.py
  plugins/cosigner_pool/qt.py
Labels: UX and usability, bug, enhancement

#1127 raw opreturn in URIs
  gui/qt/main_window.py
  lib/web.py
Labels: enhancement
