Repository Electron-Cash/Electron-Cash, pull requests merged in 2019-03, with the labels that each got.

#1184 Fully close wallet + Many PyQt memory leaks fixed
  gui/qt/__init__.py
  gui/qt/exception_window.py
  gui/qt/main_window.py
  gui/qt/util.py
  lib/network.py
  lib/synchronizer.py
  lib/util.py
  lib/verifier.py
  lib/wallet.py
Labels: Do Not Merge (Yet!), performance / optimization

#1185 Fixed a bunch of bugs in wallet
  gui/qt/main_window.py
  lib/synchronizer.py
  lib/verifier.py
  lib/wallet.py
Labels: bug

#1187 Network: 'updated' callback split into: 'wallet_updated' , 'blockchain_updated'
  gui/kivy/main_window.py
  gui/qt/main_window.py
  gui/qt/network_dialog.py
  gui/stdio.py
  gui/text.py
  ios/ElectronCash/app.py
  ios/ElectronCash/electroncash_gui/ios_native/gui.py
  lib/network.py
  lib/synchronizer.py
  lib/verifier.py
  lib/wallet.py
Labels: Nits / Refactoring

#1215 [Qt] Performance improvement for the 5 major tab widgets
  gui/qt/address_list.py
  gui/qt/contact_list.py
  gui/qt/history_list.py
  gui/qt/request_list.py
  gui/qt/util.py
  gui/qt/utxo_list.py
Labels: UX and usability, performance / optimization

#1226 Add shuffle.electroncash.dk with .onion
  plugins/shuffle/servers.json
Labels: CashShuffle

#1228 Option to disable libsecp256k1 build
  setup.py
Labels: packaging
