Repository Electron-Cash/Electron-Cash, pull requests merged in 2019-06, with the labels that each got.

#1409 Add script to automate submission to VirusTotal and MetaDefender
  contrib/submit_av.sh
Labels: enhancement, packaging

#1416 Windows: Recreate the ico file to support high resolutions
  icons/electron.ico
Labels: Windows, packaging

#1423 Icons: Use recreated clock icons by the Simple Ledger devs
  contrib/gen_icons.sh
  gui/qt/history_list.py
  gui/qt/icons.py
  icons.qrc
  icons/clock1.ico
  icons/clock1.png
  icons/clock1.svg
  icons/clock2.ico
  icons/clock2.png
  icons/clock2.svg
  icons/clock3.ico
  icons/clock3.png
  icons/clock3.svg
  icons/clock4.ico
  icons/clock4.png
  icons/clock4.svg
  icons/clock5.ico
  icons/clock5.png
  icons/clock5.svg
Labels: UX and usability, enhancement

#1442 OpenAlias: Change prefix and fix code rot
  gui/qt/paytoedit.py
  lib/contacts.py
Labels: bug

#1444 AppImage: Make build reproducible
  contrib/build-linux/appimage/_build.sh
Labels: Linux, Security & Privacy, packaging

#1446 AppImage: Improve reproducible Python build reliability on Linux
  contrib/build-linux/appimage/_build.sh
  contrib/build-linux/appimage/patches/python-3.6.8-reproducible-buildinfo.diff
Labels: Linux, Security & Privacy, packaging

#1452 AppImage: Fix webbrowser.open not opening links
  gui/qt/address_list.py
  gui/qt/contact_list.py
  gui/qt/history_list.py
  gui/qt/main_window.py
  gui/qt/util.py
Labels: Linux, packaging, workarounds

#1454 PyInstaller: Rebuild bootloader from source using MinGW
  contrib/build-wine/_build.sh
  contrib/requirements/requirements-wine-build.txt
Labels: False Positive, Windows, packaging

#1456 Fix #1223 "Disappearing Menu Actions" bug
  plugins/shuffle/qt.py
Labels: Qt, UX and usability, bug

#1463 Preferences: Fix empty video device when value hasn't been set
  gui/qt/main_window.py
Labels: UX and usability

#1461 AppImage: Remove unused binaries and some redundant build commands
  contrib/build-linux/appimage/_build.sh
Labels: Linux, packaging

#1466 Icons: Replace tray / app icon with SVG version
  gui/qt/__init__.py
  gui/qt/icons.py
  gui/qt/installwizard.py
  icons.qrc
  icons/electron-cash.svg
  icons/electron.svg
  icons/electron_dark_icon .png
  icons/electron_dark_icon.png
  icons/electron_dark_icon.svg
  icons/electron_light_icon.png
  icons/electron_light_icon.svg
Labels: UX and usability, enhancement

#1465 Build: Drop Cython
  contrib/build-linux/appimage/_build.sh
  contrib/deterministic-build/requirements-hw.txt
  contrib/requirements/requirements-hw.txt
Labels: packaging

#1471 KeepKey: Fix device enumeration on Windows 10 build 1903
  plugins/keepkey/keepkey.py
Labels: hardware wallets, workarounds

#1477 Localization: Default to system language and improve dialog
  gui/qt/main_window.py
  lib/i18n.py
  lib/utils/__init__.py
  lib/utils/macos.py
  lib/utils/unicode_tools.py
  setup.py
Labels: Nits / Refactoring, Qt, UX and usability

#1479 Ledger: Fix 2FA dialog with Legacy devices and multiple outputs
  plugins/ledger/ledger.py
Labels: bug, hardware wallets

#1487 Build: Protect against PGP keyserver poisoning attack
  contrib/build-wine/_build.sh
  contrib/build-wine/pgp/7ed10b6531d7c8e1bc296021fc624643487034e5.asc
Labels: Security & Privacy, Windows, packaging
