Repository Electron-Cash/Electron-Cash, pull requests merged in 2019-12, with the labels that each got.

#1711 Remove unused sip dependency for Python 3.8 compatibility
  contrib/requirements/requirements-binaries.txt
Labels: packaging

#1715 Patch: [satochip] Electron crashes when cancelling a PIN change or seed reset
  plugins/satochip/qt.py
  plugins/satochip/satochip.py
Labels: hardware wallets

#1714 Pubkeys: Update with pubkeys from keys-n-hashes
  pubkeys/axelkey.txt
  pubkeys/calinkey.txt
  pubkeys/jamescramerkey.txt
  pubkeys/jonaldkey.txt
  pubkeys/jonaldkey2.txt
  pubkeys/kyuupichan.asc
  pubkeys/markblundebergkey.asc
Labels: Security & Privacy, packaging
