Repository Electron-Cash/Electron-Cash, pull requests merged in 2019-07, with the labels that each got.

#1489 AppImage: Upgrade to Ubuntu 16.04 as base
  contrib/build-linux/appimage/Dockerfile_ub1404
  contrib/build-linux/appimage/Dockerfile_ub1604
  contrib/build-linux/appimage/build.sh
Labels: Linux, packaging

#1491 AppImage: Fix some warnings and speed up build
  contrib/build-linux/appimage/_build.sh
Labels: Linux, Nits / Refactoring, packaging, performance / optimization

#1492 AppImage: Make color emojis available on more platforms
  contrib/build-linux/appimage/Dockerfile_ub1604
  contrib/build-linux/appimage/_build.sh
  contrib/build-linux/appimage/apprun.sh
  contrib/build-linux/appimage/test-freetype.py
Labels: Qt, UX and usability, WantWantWant, packaging

#1496 Fonts: Add Google Noto Color Emoji font subset
  contrib/build-linux/appimage/_build.sh
  contrib/fonts/.gitignore
  contrib/fonts/emojis.ttf
  contrib/fonts/emojis.txt
  contrib/fonts/emojis_license.txt
  contrib/fonts/make_emojis
  gui/qt/__init__.py
  gui/qt/main_window.py
Labels: Linux, Qt, UX and usability, packaging

#1499 Translations: Add support for plural forms
  gui/qt/transaction_dialog.py
  lib/i18n.py
  lib/wallet.py
Labels: i18n & Translation

#1500 Ledger: Fix OP_RETURN data causing exception
  plugins/ledger/ledger.py
Labels: bug, hardware wallets

#1506 Liberalize transaction deserializer and restrict merkle node checker.
  lib/transaction.py
  lib/verifier.py
Labels: enhancement

#1518 Button Editor: Fix keypress events going to the editor when the buttons are focused
  gui/qt/address_dialog.py
  gui/qt/main_window.py
  gui/qt/paytoedit.py
  gui/qt/qrtextedit.py
  gui/qt/util.py
Labels: Qt, UX and usability, Windows, bug

#1519 Remove address output requirement for bitbox
  plugins/digitalbitbox/digitalbitbox.py
Labels: enhancement, hardware wallets

#1520 HW wallets: Generalize the validate_op_return_output_and_get_data
  plugins/hw_wallet/plugin.py
  plugins/keepkey/keepkey.py
  plugins/ledger/ledger.py
Labels: Nits / Refactoring, hardware wallets

#1522 CashAccounts: Make all "copy" operations in app append the emoji char
  gui/qt/address_list.py
  gui/qt/cashacctqt.py
  gui/qt/contact_list.py
  gui/qt/main_window.py
  gui/qt/transaction_dialog.py
  lib/cashacct.py
Labels: Cash Accounts, UX and usability

#1527 AppImage: Add script to use Python interpreter from extracted AppImage
  contrib/build-linux/appimage/_build.sh
  contrib/build-linux/appimage/scripts/apprun.sh
  contrib/build-linux/appimage/scripts/common.conf
  contrib/build-linux/appimage/scripts/python.sh
  contrib/build-linux/appimage/scripts/test-fontconfig.py
  contrib/build-linux/appimage/scripts/test-freetype.py
Labels: packaging

#1529 CashAccounts: Added cashacct.electroncash.dk as a server
  lib/cashacct.py
Labels: Cash Accounts

#1530 Icons: Make palette swaps of the new icon for tray and optimize icons
  gui/qt/icons.py
  icons/electron-cash.svg
  icons/electron.ico
  icons/electron_dark_icon.svg
  icons/electron_light_icon.svg
Labels: UX and usability, enhancement

#1532 Qt GUI Fix: On Python 3.7.3, PyQt5 5.12.3+, signals not cleaned up
  gui/qt/address_list.py
  gui/qt/contact_list.py
  gui/qt/main_window.py
  gui/qt/utxo_list.py
Labels: Qt, workarounds

#1535 Translation: Defer translation lookup of some strings
  gui/qt/fee_slider.py
  gui/qt/invoice_list.py
  gui/qt/main_window.py
  gui/qt/request_list.py
  gui/qt/util.py
  lib/util.py
  lib/wallet.py
Labels: i18n & Translation

#1537 Fonts: Use a more safe fontconfig override
  gui/qt/data/fonts.xml
Labels: Linux, UX and usability, packaging

#1538 Build: Set a fixed umask before starting Docker
  contrib/base.sh
  contrib/build-linux/appimage/_build.sh
Labels: packaging

#1543 Fonts: Use UNIX line endings for fonts.xml
  gui/qt/data/fonts.xml
Labels: Nits / Refactoring

#1544 Windows & Linux - FreeType & fontconfig logic tweaks + prefs options
  gui/qt/__init__.py
  gui/qt/main_window.py
Labels: Linux, Qt, Windows, packaging

#1547 CashAccounts: Added parsing & integration of cashacct: URIs
  contrib/build-wine/electron-cash.nsi
  contrib/osx/make_osx
  electron-cash
  electron-cash.desktop
  gui/qt/main_window.py
  gui/qt/paytoedit.py
  lib/cashacct.py
  lib/web.py
  org.electroncash.ElectronCash.appdata.xml
Labels: Cash Accounts

#1545 Linux & Windows: Fix for Preferences crash caused by lazy-loading QtMultimedia
  gui/qt/main_window.py
Labels: Linux, Qt, Windows, workarounds

#1548 Build: Only set SUDO if it is not defined already
  contrib/build-linux/appimage/build.sh
  contrib/build-linux/srcdist_docker/build.sh
  contrib/build-wine/build.sh
Labels: packaging

#1549 Build: Improvements for automatic builds and reproducibility
  contrib/base.sh
  contrib/build-linux/appimage/build.sh
  contrib/build-linux/srcdist_docker/Dockerfile
  contrib/build-linux/srcdist_docker/_build.sh
  contrib/build-linux/srcdist_docker/build.sh
  contrib/build-wine/_build.sh
  contrib/build-wine/build.sh
  contrib/build-wine/docker/Dockerfile
  contrib/build-wine/electron-cash.nsi
  contrib/make_linux_sdist
  setup.py
Labels: enhancement, packaging, performance / optimization

#1550 Wine Build: Fix uninitialized memory in NSIS making build non-reproducible
  contrib/build-wine/_build.sh
  icons/electron.ico
Labels: Windows, packaging, workarounds

#1556 KeepKey: Fix WebUSB on Windows 10 1903
  contrib/build-wine/_build.sh
  plugins/keepkey/keepkey.py
Labels: Windows, hardware wallets, workarounds
