Repository Electron-Cash/Electron-Cash, pull requests merged in 2019-02, with the labels that each got.

#1146 Append HMAC to BitBox messages
  plugins/digitalbitbox/digitalbitbox.py
Labels: hardware wallets

#1151 [Android] Add buildFlavours for mainnet or testnet
  android/app/build.gradle
  android/app/src/main/java/org/electroncash/electroncash3/Addresses.kt
  android/app/src/main/java/org/electroncash/electroncash3/App.kt
  android/app/src/main/java/org/electroncash/electroncash3/Daemon.kt
  android/build.sh
Labels: android, enhancement

#986 add note about BIP38 keys on sweep dialog
  gui/qt/main_window.py
  lib/keystore.py
Labels: Do Not Merge (Yet!), UX and usability

#1163 remove lib/enum.py and replace with Python's enum
  lib/address.py
  lib/enum.py
Labels: Nits / Refactoring
