Repository Electron-Cash/Electron-Cash, pull requests merged in 2019-05, with the labels that each got.

#1333 AppImage libusb / PyQt5 fix
  contrib/build-linux/appimage/_build.sh
  plugins/ledger/qt.py
Labels: Linux, bug, hardware wallets

#1332 Schnorr Redux
  lib/ecc_fast.py
  lib/schnorr.py
  lib/secp256k1.py
Labels: enhancement

#1339 Add pure python schnorr
  lib/schnorr.py
Labels: enhancement

#1337 Add Schnorr signature capability to the UI
  gui/qt/main_window.py
  gui/qt/transaction_dialog.py
  lib/coinchooser.py
  lib/transaction.py
  lib/wallet.py
Labels: enhancement

#1345 Linux: Add helper dialog to install udev rules
  gui/qt/main_window.py
  gui/qt/udev_installer.py
Labels: Linux, enhancement, hardware wallets

#1346 Linux: Check for plugdev group in udev installer
  gui/qt/udev_installer.py
Labels: Linux, UX and usability, enhancement, hardware wallets

#1365 Zbar: Bump to upstream master and add Linux build
  contrib/build-linux/appimage/Dockerfile_ub1404
  contrib/build-linux/appimage/_build.sh
  contrib/build-wine/_build.sh
  contrib/make_secp
  contrib/make_zbar
  lib/qrscanner.py
  setup.py
Labels: UX and usability, Windows

#1371 Various fixes and improvements to the button / pay to editor
  gui/qt/paytoedit.py
  gui/qt/util.py
Labels: Qt

#1373 Ledger: Make messages refer to the device by name and enable localization
  plugins/ledger/ledger.py
Labels: UX and usability, hardware wallets

#1390 AppImage: Clean up dependencies of the Docker image
  contrib/build-linux/appimage/Dockerfile_ub1404
Labels: Linux, packaging

#1387 Refactor sign_schnorr tx generation mechanics to be per-input
  gui/qt/main_window.py
  lib/coinchooser.py
  lib/transaction.py
  lib/wallet.py
  plugins/digitalbitbox/digitalbitbox.py
Labels: Nits / Refactoring

#1393 Support older versions of Qt5
  gui/qt/main_window.py
  gui/qt/qrreaderutil.py
  gui/qt/qrtextedit.py
Labels: Qt, enhancement, workarounds

#1397 Fetch Input data for TX's (Amount, Address, etc) -- for the Transaction Dialog, asynchronously
  gui/qt/main_window.py
  gui/qt/transaction_dialog.py
  gui/qt/util.py
  lib/network.py
  lib/transaction.py
Labels: UX and usability

#1407 Implement CoinText
  gui/qt/main_window.py
  gui/qt/paytoedit.py
Labels: enhancement
