Repository Electron-Cash/Electron-Cash, pull requests merged in 2019-04, with the labels that each got.

#959 [WIP] Fix the support for Ledger HW1/Nano legacy hardware w/o touching Nano S/Blue
  plugins/ledger/auth2fa.py
  plugins/ledger/ledger.py
Labels: Do Not Merge (Yet!), hardware wallets

#1251 Hw Wallets: Improve how missing libraries are handled
  contrib/requirements/requirements-hw.txt
  gui/qt/installwizard.py
  lib/base_wizard.py
Labels: UX and usability, enhancement, hardware wallets

#1254 Hw Wallets: Show proper error message when trying to sign a tx with OP_RETURN
  plugins/digitalbitbox/digitalbitbox.py
  plugins/ledger/ledger.py
Labels: hardware wallets

#1265 Thin generated OSX .app binary by removing un-needed Qt Libs
  contrib/osx/osx.spec
Labels: macOS, packaging

#1266 Windows: Add missing opengl libs to support software rendering and ANGLE
  contrib/build-wine/deterministic.spec
  contrib/build-wine/electron-cash.nsi
  lib/commands.py
  lib/daemon.py
Labels: Windows, packaging

#1268 [OSX] Make a fancy dmg
  contrib/osx/background.png
  contrib/osx/dmg_settings.py
  contrib/osx/make_osx
Labels: macOS, packaging

#1271 Harden Build Process -- use pip package hashes and verify downloaded packages
  contrib/base.sh
  contrib/build-wine/_build.sh
  contrib/deterministic-build/find_restricted_dependencies.py
  contrib/deterministic-build/requirements-binaries.txt
  contrib/deterministic-build/requirements-hw.txt
  contrib/deterministic-build/requirements.txt
  contrib/freeze_packages.sh
  contrib/osx/make_osx
  contrib/requirements/requirements-binaries.txt
  contrib/requirements/requirements-hw.txt
Labels: Security & Privacy, packaging

#1272 Add Linux AppImage Build
  contrib/base.sh
  contrib/build-linux/README.md
  contrib/build-linux/appimage/Dockerfile
  contrib/build-linux/appimage/README.md
  contrib/build-linux/appimage/_build.sh
  contrib/build-linux/appimage/apprun.sh
  contrib/build-linux/appimage/build.sh
Labels: Linux, Security & Privacy, packaging

#1281 Ledger: Support OP_RETURN and multiple transaction outputs
  plugins/hw_wallet/plugin.py
  plugins/ledger/ledger.py
Labels: enhancement, hardware wallets

#1289 Implemented BIP38 Key Importing
  gui/qt/bip38_importer.py
  gui/qt/installwizard.py
  gui/qt/main_window.py
  lib/base_wizard.py
  lib/bitcoin.py
  lib/keystore.py
Labels: Qt, Security & Privacy, UX and usability, enhancement

#1295 Windows: Make console work properly
  contrib/build-wine/deterministic.spec
  contrib/deterministic-build/requirements-binaries.txt
  contrib/requirements/requirements-binaries.txt
  electron-cash
  lib/winconsole.py
Labels: Command Line, Windows, enhancement

#1298 Ledger: Remove non-working websocket 2FA for legacy ledger devices
  plugins/ledger/auth2fa.py
  plugins/ledger/ledger.py
Labels: bug, hardware wallets

#1308 Console: Add warning dialog to protect against social engineering attacks
  gui/qt/console.py
  gui/qt/main_window.py
Labels: Qt, Security & Privacy, enhancement

#1318 Qt: Input widgets update
  gui/qt/address_dialog.py
  gui/qt/main_window.py
  gui/qt/util.py
Labels: Qt, UX and usability
