Repository Electron-Cash/Electron-Cash, pull requests merged in 2019-09, with the labels that each got.

#1602 Add SLP Awareness to prevent token burn
  gui/qt/util.py
  gui/qt/utxo_list.py
  lib/slp/__init__.py
  lib/slp/exceptions.py
  lib/slp/slp.py
  lib/tests/test_slp.py
  lib/wallet.py
  plugins/shuffle/qt.py
  setup.py
Labels: SLP, enhancement

#1607 Fix Android sync performance
  lib/util.py
Labels: android, performance / optimization

#1612 Implement BIP70 properly on Qt and iOS
  gui/qt/main_window.py
  ios/ElectronCash/electroncash_gui/ios_native/gui.py
Labels: bug

#1609 [WIP] Ledger Nano X Fixes
  gui/qt/util.py
  lib/keystore.py
  plugins/hw_wallet/plugin.py
  plugins/hw_wallet/qt.py
  plugins/ledger/ledger.py
Labels: Do Not Merge (Yet!)

#1617 Configure payment_url to include payment request ID
  lib/wallet.py
Labels: workarounds

#1620 p2sh: Fix coin tracking / balance, etc for esoteric scriptSigs/redeemScripts in inputs
  lib/wallet.py
Labels: enhancement

#1614 Android fixes
  android/Dockerfile
  android/README.md
  android/app/build.gradle
  android/app/src/main/java/org/electroncash/electroncash3/Addresses.kt
  android/app/src/main/java/org/electroncash/electroncash3/App.kt
  android/app/src/main/java/org/electroncash/electroncash3/Contacts.kt
  android/app/src/main/java/org/electroncash/electroncash3/Daemon.kt
  android/app/src/main/java/org/electroncash/electroncash3/Dialog.kt
  android/app/src/main/java/org/electroncash/electroncash3/Main.kt
  android/app/src/main/java/org/electroncash/electroncash3/Network.kt
  android/app/src/main/java/org/electroncash/electroncash3/NewWallet.kt
  android/app/src/main/java/org/electroncash/electroncash3/Requests.kt
  android/app/src/main/java/org/electroncash/electroncash3/Send.kt
  android/app/src/main/java/org/electroncash/electroncash3/Settings.kt
  android/app/src/main/java/org/electroncash/electroncash3/Transactions.kt
  android/app/src/main/java/org/electroncash/electroncash3/Util.kt
  android/app/src/main/python/electroncash_gui/android/console.py
  android/app/src/main/python/electroncash_gui/android/strings.py
  android/app/src/main/res/layout/settings.xml
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
Labels: android

#1623 Fix Android console unit_test function
  android/app/src/main/python/electroncash_gui/android/console.py
Labels: android

#1624 i18n: Add support for pgettext and npgettext with msgctxt
  contrib/make_locale
  gui/qt/main_window.py
  gui/qt/network_dialog.py
  gui/qt/transaction_dialog.py
  ios/ElectronCash/electroncash_gui/ios_native/network_dialog.py
  ios/ElectronCash/electroncash_gui/ios_native/prefs.py
  ios/ElectronCash/electroncash_gui/ios_native/wallets.py
  lib/i18n.py
Labels: enhancement, i18n & Translation
