Repository Electron-Cash/Electron-Cash, pull requests merged in 2020-08, with the labels that each got.

#1929 Tests: Fix failing host name test and add wildcard tests
  lib/tests/test_interface.py
Labels: bug

#1930 Travis: Make it work again for Python 3.6, 3.7 and 3.8
  .travis.yml
  contrib/requirements/requirements-travis.txt
  tox.ini
Labels: tests

#1927 CashFusion: Show disabled icon and add message on non-fusable wallets
  plugins/fusion/qt.py
Labels: Cash Fusion, UX and usability

#1934 dnssec: fix compat with dnspython 1.16 and 2.0.0
  contrib/requirements/requirements.txt
  lib/dnssec.py
  lib/interface.py
  lib/tests/__init__.py
  lib/tests/test_dnssec.py
Labels: bug

#1940 CashShuffle: Remove unmaintained tests
  plugins/shuffle_deprecated/tests/config.ini
  plugins/shuffle_deprecated/tests/functional/test_coin_shuffle.py
  plugins/shuffle_deprecated/tests/functional/test_coins.py
  plugins/shuffle_deprecated/tests/functional/test_messages.py
  plugins/shuffle_deprecated/tests/test.py
  plugins/shuffle_deprecated/tests/test_announcement.py
  plugins/shuffle_deprecated/tests/test_bad_connections.py
  plugins/shuffle_deprecated/tests/test_bad_hash.py
  plugins/shuffle_deprecated/tests/test_bad_shuffling.py
  plugins/shuffle_deprecated/tests/test_correct_execution.py
  plugins/shuffle_deprecated/tests/test_network_fault.py
  tox.ini
Labels: tests

#1951 Add more tiers for fusion server
  plugins/fusion/server.py
Labels: Cash Fusion, enhancement

#1952 Add Blockchain.com mainnet and testnet explorers
  lib/web.py
Labels: UX and usability

#1953 Fusion: Remove example server
  plugins/fusion/conf.py
Labels: UX and usability

#1949 git sanity: enforce "git checkout commithash" actually pulls commit
  contrib/build-linux/appimage/_build.sh
  contrib/build-wine/_build.sh
  contrib/osx/make_osx
  ios/make_ios_project.sh
Labels: Security & Privacy, packaging

#1941 Tor: Make the messages refer to a specific Tor binary
  gui/qt/network_dialog.py
  lib/tor/controller.py
  plugins/fusion/qt.py
Labels: Cash Fusion, Security & Privacy, UX and usability

#1954 Add support for the ASERTi3-2d DAA for the Nov. 15th, 2020 Upgrade
  lib/asert_daa.py
  lib/blockchain.py
  lib/networks.py
Labels: enhancement

#1958 CashFusion: more flexible fee fuzzing logic; more funds safety checks
  plugins/fusion/fusion.py
Labels: Cash Fusion, enhancement

#1809 Made PyQt5 optional by default and installable by [full] or [gui] extra requires
  setup.py
Labels: packaging

#1972 Fix make_locale to be more pythonic
  contrib/make_locale
Labels: i18n & Translation, packaging

#1974 Add testnet4
  contrib/build-wine/deterministic.spec
  contrib/osx/osx.spec
  electron-cash
  lib/blockchain.py
  lib/commands.py
  lib/networks.py
  lib/servers_testnet4.json
  lib/simple_config.py
  setup.py
Labels: enhancement
