Repository Electron-Cash/Electron-Cash, pull requests merged in 2020-11, with the labels that each got.

#2036 Add Loping.net block explorers, add TestNet4 / ScaleNet explorer list
  electroncash/web.py
Labels: enhancement

#2061 Ledger: Update USB ids for app-bitcoin version >= 1.5.1
  electroncash_plugins/ledger/ledger.py
Labels: hardware wallets

#2077 [fusion] fix minor race leading to exception
  electroncash_plugins/fusion/plugin.py
Labels: Cash Fusion, bug
