Repository Electron-Cash/Electron-Cash, pull requests merged in 2020-10, with the labels that each got.

#2009 Ledger: Update btchip-python version for deterministic build
  contrib/deterministic-build/requirements-hw.txt
Labels: hardware wallets, packaging

#2011 Add paymentrequest tests
  lib/tests/test_paymentrequests.py
Labels: tests

#2015 Use locale atof when sorting columns
  gui/qt/util.py
Labels: i18n & Translation

#2016 Add Bitcoin Unlimited block explorer
  lib/web.py
Labels: UX and usability

#2022 Disable `cointext:` support from send tab & remove cointext code
  electroncash_gui/qt/main_window.py
  electroncash_gui/qt/paytoedit.py
Labels: High Priority

#2027 Fix typo in transaction dialog
  electroncash_gui/qt/transaction_dialog.py
Labels: UX and usability

#2028 [Fusion] Various fixes to starting and stopping behaviour
  electroncash_plugins/fusion/fusion.py
  electroncash_plugins/fusion/plugin.py
  electroncash_plugins/fusion/qt.py
Labels: Cash Fusion

#2030 [fusion] better handling on interactions with electrumx server
  electroncash_plugins/fusion/fusion.py
  electroncash_plugins/fusion/server.py
  electroncash_plugins/fusion/validation.py
Labels: Cash Fusion

#2031 daemonize Tor subprocess
  electroncash/tor/controller.py
Labels: enhancement
