Repository Electron-Cash/Electron-Cash, pull requests merged in 2020-12, with the labels that each got.

#2093 QR scan from multiple screen and add context menu
  electroncash_gui/qt/qrtextedit.py
Labels: enhancement

#2106 Remove expensive json.dumps calls in storage.put
  electroncash/storage.py
Labels: performance / optimization

#2110 Use faster JSON encoder settings when wallet is encrypted
  electroncash/storage.py
Labels: performance / optimization

#2113 Fix redundant calls to save_addresses during synchronization
  electroncash/wallet.py
Labels: performance / optimization

#2115 Tor: Fix proxy bypass for stem version 1.8.0
  electroncash/network.py
  electroncash/tor/__init__.py
  electroncash/tor/controller.py
Labels: workarounds

#2095 Refactor main() into functions
  electron-cash
Labels: Nits / Refactoring, code quality
