Repository Electron-Cash/Electron-Cash, pull requests merged in 2020-07, with the labels that each got.

#1917 Event: Replace forced main thread invocation with function decorator
  gui/qt/network_dialog.py
  lib/util.py
  lib/utils/event.py
Labels: enhancement

#1918 SSL Certs: Accept wildcard certs, accept CA-signed replacing pinned
  lib/interface.py
Labels: bug

#1920 Add electroncash.de block explorer
  lib/web.py
Labels: UX and usability

#1919 Network: Show problematic pinned certificates and allow unpinning
  contrib/fonts/glyphs.txt
  gui/qt/data/ecsupplemental_lnx.ttf
  gui/qt/data/ecsupplemental_win.ttf
  gui/qt/network_dialog.py
  lib/interface.py
  lib/network.py
Labels: Security & Privacy, UX and usability, enhancement

#1921 Merge cashfusion branch
  contrib/build-wine/deterministic.spec
  contrib/osx/osx.spec
  gui/qt/main_window.py
  lib/version.py
  lib/wallet.py
  plugins/fusion/Cash Fusion Logo - No Text Gray.svg
  plugins/fusion/Cash Fusion Logo - No Text.svg
  plugins/fusion/__init__.py
  plugins/fusion/cmdline.py
  plugins/fusion/comms.py
  plugins/fusion/compileproto.sh
  plugins/fusion/conf.py
  plugins/fusion/connection.py
  plugins/fusion/covert.py
  plugins/fusion/encrypt.py
  plugins/fusion/fusion.py
  plugins/fusion/fusion_pb2.py
  plugins/fusion/pedersen.py
  plugins/fusion/plugin.py
  plugins/fusion/protobuf/fusion.proto
  plugins/fusion/protocol.py
  plugins/fusion/qt.py
  plugins/fusion/red_exclamation.png
  plugins/fusion/server.py
  plugins/fusion/tests/test_encrypt.py
  plugins/fusion/tests/test_pedersen.py
  plugins/fusion/util.py
  plugins/fusion/validation.py
  plugins/shuffle_deprecated/__init__.py
  plugins/shuffle_deprecated/client.py
  plugins/shuffle_deprecated/coin_utils.py
  plugins/shuffle_deprecated/comms.py
  plugins/shuffle_deprecated/conf_keys.py
  plugins/shuffle_deprecated/crypto.py
  plugins/shuffle_deprecated/message_pb2.py
  plugins/shuffle_deprecated/messages.py
  plugins/shuffle_deprecated/protobuf/message.proto
  plugins/shuffle_deprecated/qt.py
  plugins/shuffle_deprecated/qt_status_bar_mgr.py
  plugins/shuffle_deprecated/round.py
  plugins/shuffle_deprecated/servers.json
  plugins/shuffle_deprecated/tests/config.ini
  plugins/shuffle_deprecated/tests/functional/test_coin_shuffle.py
  plugins/shuffle_deprecated/tests/functional/test_coins.py
  plugins/shuffle_deprecated/tests/functional/test_messages.py
  plugins/shuffle_deprecated/tests/test.py
  plugins/shuffle_deprecated/tests/test_announcement.py
  plugins/shuffle_deprecated/tests/test_bad_connections.py
  plugins/shuffle_deprecated/tests/test_bad_hash.py
  plugins/shuffle_deprecated/tests/test_bad_shuffling.py
  plugins/shuffle_deprecated/tests/test_correct_execution.py
  plugins/shuffle_deprecated/tests/test_network_fault.py
  setup.py
  tox.ini
Labels: Cash Fusion

#1915 Update plugin for Satochip hardware wallet to support latest firmware v0.11
  contrib/build-linux/appimage/Dockerfile_ub1604
  contrib/build-linux/appimage/_build.sh
  contrib/deterministic-build/requirements-hw.txt
  contrib/deterministic-build/requirements-satochip.txt
  contrib/requirements/requirements-hw.txt
  plugins/satochip/CardConnector.py
  plugins/satochip/CardDataParser.py
  plugins/satochip/JCconstants.py
  plugins/satochip/README.rst
  plugins/satochip/TxParser.py
  plugins/satochip/ecc.py
  plugins/satochip/qt.py
  plugins/satochip/satochip.py
  plugins/satochip/zzbroken_test_CardConnector.py
  plugins/satochip_2FA/__init__.py
  plugins/satochip_2FA/qt.py
  setup.py
Labels: High Priority, hardware wallets
