Repository Electron-Cash/Electron-Cash, pull requests merged in 2020-01, with the labels that each got.

#1747 Server list: Add 'display' key to give Tor servers a short name
  gui/qt/network_dialog.py
Labels: Qt, UX and usability

#1750 Network dialog: Fix missing localization string for found Tor proxy
  gui/qt/network_dialog.py
Labels: i18n & Translation

#1751 Network dialog: Add tor icon to node list as well
  gui/qt/network_dialog.py
Labels: Qt, UX and usability

#1749 Network dialog: Fix not showing .onions before switching to the Proxy tab
  gui/qt/network_dialog.py
Labels: Qt, UX and usability

#1753 Build: Update wine libsecp256k1 commit for new repo
  contrib/build-wine/_build.sh
Labels: Windows, packaging

#1754 Network dialog: Correctly handle finding a different tor proxy
  gui/qt/network_dialog.py
Labels: UX and usability, bug

#1755 Network dialog: Change to some better looking icons
  contrib/fonts/glyphs.txt
  contrib/fonts/make_emojis
  gui/qt/data/ecsupplemental_lnx.ttf
  gui/qt/data/ecsupplemental_win.ttf
  gui/qt/network_dialog.py
Labels: UX and usability

#1776 Build: Fix regression causing newer glibc to be pulled into AppImage
  contrib/base.sh
  contrib/build-linux/appimage/Dockerfile_ub1604
Labels: Linux, bug, packaging

#1786 Tweak / add more broadcast error messages
  lib/network.py
Labels: enhancement
