Repository Electron-Cash/Electron-Cash, pull requests merged in 2020-02, with the labels that each got.

#1647 Add change-address reservation subsystem
  gui/qt/main_window.py
  lib/wallet.py
  plugins/shuffle/client.py
  plugins/shuffle/coin_utils.py
  plugins/shuffle/qt.py
Labels: Nits / Refactoring, enhancement

#1746 Add create/restore commands in RPC
  .gitignore
  lib/commands.py
  lib/mnemonic.py
  lib/simple_config.py
  lib/tests/test_wallet.py
  lib/wallet.py
Labels: Command Line, enhancement

#1802 Added payment_received event
  gui/qt/invoice_list.py
  gui/qt/request_list.py
  gui/qt/util.py
  lib/commands.py
  lib/network.py
  lib/paymentrequest.py
  lib/wallet.py
Labels: enhancement

#1813 Status bar: Add missing localization strings and improve code
  gui/qt/main_window.py
Labels: Nits / Refactoring, i18n & Translation

#1818 Small shuffle fixes
  plugins/shuffle/qt.py
  setup.py
Labels: Nits / Refactoring

#1819 Faster Network connections
  lib/interface.py
  lib/network.py
  lib/util.py
Labels: performance / optimization
