Repository Electron-Cash/Electron-Cash, pull requests merged in 2021-02, with the labels that each got.

#2145 Tor: Update message parser to support version 0.4.5.x
  electroncash/tor/controller.py
Labels: enhancement

#2144 AppImage: Build using Ubuntu 18.04 (Bionic)
  contrib/build-linux/appimage/Dockerfile_ub1604
  contrib/build-linux/appimage/Dockerfile_ub1804
  contrib/build-linux/appimage/_build.sh
  contrib/build-linux/appimage/build.sh
  contrib/build-linux/appimage/scripts/apprun.sh
  contrib/build-linux/appimage/scripts/common.conf
  contrib/build-linux/appimage/scripts/common.sh
  contrib/build-linux/appimage/scripts/python.sh
  contrib/build-linux/appimage/scripts/test-fontconfig.py
  contrib/build-linux/appimage/scripts/test-freetype.py
Labels: packaging

#2129 Warn if a legacy addres is used
  electroncash/address.py
  electroncash_gui/qt/main_window.py
Labels: UX and usability, enhancement

#2155 Wine: Update to version 6.0
  contrib/build-wine/docker/Dockerfile
  contrib/build-wine/docker/opensuse.key
  contrib/build-wine/docker/winehq.key
Labels: Windows, packaging

#2158 Tests: Fix missing dnspython dependency causing DNSSEC tests to fail
  .travis.yml
  tox.ini
Labels: tests

#2159 AppImage: Build all binaries except PyQt5
  contrib/build-linux/appimage/Dockerfile_ub1804
  contrib/build-linux/appimage/_build.sh
  contrib/deterministic-build/requirements-hw.txt
  contrib/requirements/requirements-hw.txt
Labels: Linux, Security & Privacy, packaging

#2161 Windows: Use PyInstaller version 4.2
  contrib/build-wine/_build.sh
  contrib/build-wine/requirements-wine-build.txt
  contrib/requirements/requirements-wine-build.txt
Labels: Windows, packaging

#2160 Build: Add git_describe_filtered helper
  contrib/base.sh
  contrib/build-linux/appimage/_build.sh
  contrib/build-wine/_build.sh
  contrib/make_linux_sdist
  contrib/osx/make_osx
Labels: code quality, packaging

#2162 Build: Update Python to version 3.8.7
  contrib/base.sh
  contrib/build-linux/appimage/_build.sh
  contrib/build-linux/appimage/patches/python-3.8.6-reproducible-buildinfo.diff
  contrib/build-linux/appimage/scripts/common.sh
  contrib/build-wine/_build.sh
  contrib/build-wine/deterministic.spec
  contrib/build-wine/requirements-wine-build.txt
  contrib/deterministic-build/requirements-binaries.txt
  contrib/deterministic-build/requirements-build-wine.txt
  contrib/deterministic-build/requirements-hw.txt
  contrib/deterministic-build/requirements.txt
  contrib/freeze_packages.sh
  contrib/requirements/requirements-binaries.txt
  contrib/requirements/requirements-build-uninstall.txt
  contrib/requirements/requirements-build-wine.txt
  contrib/requirements/requirements-hw.txt
  contrib/requirements/requirements-wine-build.txt
Labels: enhancement, packaging

#2170 Revert RPA changes (#2006 and fixes)
  electroncash/commands.py
  electroncash/keystore.py
  electroncash/rpa/__init__.py
  electroncash/rpa/addr.py
  electroncash/rpa/paycode.py
  electroncash/schnorr.py
  electroncash/transaction.py
  electroncash/wallet.py
  setup.py
Labels: code quality
