Repository Electron-Cash/Electron-Cash, pull requests merged in 2021-03, with the labels that each got.

#2184 NSIS: Wait for the uninstaller to finish
  contrib/build-wine/electron-cash.nsi
Labels: Windows, packaging

#2185 NSIS: Ensure the process is not running when (un)installing
  contrib/build-wine/electron-cash.nsi
Labels: Windows, packaging

#2191 Build: Use git version with patch for CVE-2021-21300
  contrib/build-linux/appimage/Dockerfile_ub1804
  contrib/build-wine/docker/Dockerfile
Labels: Security & Privacy, packaging

#2199 Install Wizard: Add derivation path scanner
  electroncash/base_wizard.py
  electroncash_gui/qt/installwizard.py
Labels: Qt, enhancement

#2203 Build: Add cffi to the requirements
  contrib/deterministic-build/requirements.txt
Labels: bug, packaging

#2209 Shorten boolean expression, use double quotes
  electroncash/base_wizard.py
Labels: code quality

#2211 Style changes (from backport), small refactorings
  contrib/sign_packages
  electroncash/coinchooser.py
  electroncash/mnemonic.py
  electroncash/old_mnemonic.py
  electroncash/plot.py
  electroncash/tests/test_bitcoin.py
  electroncash_gui/qt/main_window.py
  electroncash_gui/qt/network_dialog.py
  electroncash_gui/qt/password_dialog.py
  electroncash_gui/qt/qrcodewidget.py
  electroncash_gui/qt/util.py
  electroncash_gui/stdio.py
  electroncash_gui/text.py
  electroncash_plugins/hw_wallet/cmdline.py
  electroncash_plugins/keepkey/keepkey.py
  electroncash_plugins/ledger/auth2fa.py
  electroncash_plugins/ledger/ledger.py
Labels: code quality
