Repository Electron-Cash/Electron-Cash, pull requests merged in 2022-04, with the labels that each got.

#2414 Add LNS support
  contrib/requirements/requirements.txt
  electroncash/contacts.py
  electroncash/lns.py
  electroncash/wallet.py
  electroncash_gui/qt/contact_list.py
  electroncash_gui/qt/icons.py
  electroncash_gui/qt/lnsqt.py
  electroncash_gui/qt/main_window.py
  electroncash_gui/qt/network_dialog.py
  electroncash_gui/qt/paytoedit.py
  icons.qrc
  icons/lns.png
Labels: enhancement, smartBCH

#2420 Build: Update the Wine build docker container to use the MSVC compiler
  contrib/build-wine/_build.sh
  contrib/build-wine/build.sh
  contrib/build-wine/docker/Dockerfile
  contrib/deterministic-build/requirements-build-wine.txt
  contrib/deterministic-build/requirements.txt
Labels: packaging, Windows, WantWantWant, High Priority

#2424 Build: Patch pip vendored distlib to produce deterministic zip archives
  contrib/build-wine/_build.sh
Labels: packaging, Windows

#2423 Build: Install a MSVC linker wrapper to make PE timestamps deterministic
  contrib/build-wine/docker/Dockerfile
  contrib/build-wine/docker/wrapper.cpp
  contrib/build-wine/docker/wrapper_install.bat
Labels: packaging, Windows

#2427 Add 10BCH fusion tier
  electroncash_plugins/fusion/server.py
Labels: Cash Fusion
