Repository Electron-Cash/Electron-Cash, pull requests merged in 2022-05, with the labels that each got.

#2433 CTOR workaround approach 2: Always display receives before sends (for the same block)
  electroncash/wallet.py
  electroncash_gui/qt/history_list.py
  electroncash_gui/qt/main_window.py
Labels: enhancement, workarounds, Qt

#2436 Wine: Update to version 7.7
  contrib/build-wine/docker/Dockerfile
Labels: packaging, Windows

#2441 LNS: Make the dependencies optional
  contrib/build-linux/appimage/_build.sh
  contrib/build-wine/_build.sh
  contrib/deterministic-build/requirements-build-appimage.txt
  contrib/deterministic-build/requirements-build-wine.txt
  contrib/deterministic-build/requirements-web3.txt
  contrib/deterministic-build/requirements.txt
  contrib/make_packages
  contrib/osx/make_osx
  contrib/osx/requirements-osx-build.txt
  contrib/requirements/requirements-web3.txt
  contrib/requirements/requirements.txt
  electroncash/contacts.py
  electroncash/lns.py
  electroncash/wallet.py
  electroncash_gui/qt/contact_list.py
  electroncash_gui/qt/lnsqt.py
  electroncash_gui/qt/main_window.py
  electroncash_gui/qt/network_dialog.py
  electroncash_gui/qt/paytoedit.py
  setup.py
Labels: bug, packaging, LNS

#2444 Wine: Pass additional flags to reduce junk in the binaries
  contrib/build-wine/docker/wrapper.cpp
  contrib/build-wine/docker/wrapper_install.bat
Labels: Windows, Reproducibility
