Repository Electron-Cash/Electron-Cash, pull requests merged in 2023-02, with the labels that each got.

#2547 Bump winbind
  contrib/build-wine/docker/Dockerfile
Labels: packaging

#2548 Build Android in GH Actions
  .github/workflows/build.yml
  android/Dockerfile
  android/dummykeystore.jks
Labels: android

#2551 Bump xvfb for wine build
  contrib/build-wine/docker/Dockerfile
Labels: packaging

#2559 Remove LNS and web3 dependencies
  contrib/build-linux/appimage/_build.sh
  contrib/build-wine/_build.sh
  contrib/deterministic-build/requirements-web3.txt
  contrib/freeze_packages.sh
  contrib/osx/make_osx
  contrib/requirements/requirements-web3.txt
  electroncash/contacts.py
  electroncash/lns.py
  electroncash/wallet.py
  electroncash_gui/qt/contact_list.py
  electroncash_gui/qt/icons.py
  electroncash_gui/qt/lnsqt.py
  electroncash_gui/qt/main_window.py
  electroncash_gui/qt/network_dialog.py
  electroncash_gui/qt/paytoedit.py
  icons.qrc
  icons/lns.png
  setup.py
Labels: packaging, LNS

#2560 Remove last vestige of web3 dependencies
  .github/workflows/audit.yml
  contrib/deterministic-build/requirements-build-wine.txt
Labels: LNS
