Repository Electron-Cash/Electron-Cash, pull requests merged in 2024-05, with the labels that each got.

#2840 Fix state loss when swtiching/resuming tx fragment
  android/app/src/main/java/org/electroncash/electroncash3/Main.kt
  android/app/src/main/java/org/electroncash/electroncash3/Transactions.kt
Labels: android

#2843 Exclude python versions in GitHub Actions
  .github/workflows/run-tox.yml
Labels: tests

#2854 tor: fix message reader getting stuck
  electroncash/tor/controller.py
Labels: bug

#2856 Correct variable in token_data error of add_transaction().
  electroncash/wallet.py
Labels: bug

#2857 Correct if statement for commands needing password
  electron-cash
Labels: bug
