Repository Electron-Cash/Electron-Cash, pull requests merged in 2024-07, with the labels that each got.

#2885 build: switch AppImage to gcc 10 and remove mksquashfs build
  contrib/build-linux/appimage/Dockerfile_ub2004
  contrib/build-linux/appimage/_build.sh
Labels: bug, packaging, Linux

#2886 build: fix python dev.msi installation in wine
  contrib/build-wine/_build.sh
Labels: bug, packaging, Windows

#2887 modified: contrib/deterministic-build/requirements-hw.txt
  contrib/deterministic-build/requirements-hw.txt
  contrib/requirements/requirements-hw.txt
  electroncash_plugins/trezor/clientbase.py
  electroncash_plugins/trezor/trezor.py
Labels: hardware wallets, packaging
